linters:
  fast: false
  disable-all: true
  enable:
    - revive
    - govet
    - unconvert
    - gocyclo
    - dupl
    - misspell
    - unparam
    - unused
    - typecheck
    - ineffassign
    - gocritic
    - nakedret
    - gosimple
    - prealloc

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: package-comments
        severity: warning
        disabled: true
      - name: exported
        severity: warning
        disabled: false
        arguments: ["checkPrivateReceivers", "disableStutteringCheck"]

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl